account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('update/', views.update, name='update'),
]

room/urls.py
from django.urls import path
from . import views
app_name = 'room'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.room, name='room'),

]

the_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('room/', include('room.urls', namespace='room')),
    path('', views.home, name='home')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

room/models.py
from django.db import models

# Create your models here.


class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout as logout_handler, login as auth_login
from django.views.decorators.http import require_http_methods
from django.contrib.auth.models import User
from django.db import IntegrityError
import re


def is_valid_password(password):
    regex = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
    return re.match(regex, password) is not None


def is_valid_email(email):
    regex = r'^[\w\.-]+@[a-zA-Z\d\.-]+\.[a-zA-Z]{2,}$'
    return re.match(regex, email) is not None


def is_valid_username(username):
    regex = r'^[a-zA-Z0-9_]{4,32}$'
    return re.match(regex, username) is not None


# Create your views here.
@require_http_methods(["GET", "POST"])
def login(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'GET':
        return render(request, 'account/login.html')
    if request.method == 'POST':
        password = request.POST.get('password')
        username = request.POST.get('username')
        print(username, password)
        if is_valid_password(password) == False:
            return render(request, 'account/login.html', {'error': 'Invalid Password'})
        try:
            if is_valid_username(username) == False:
                return render(request, 'account/login.html', {'error': 'Invalid Username'})
            user = authenticate(request, username=username, password=password)
        except Exception:
            if is_valid_email(username) == False:
                return render(request, 'account/login.html', {'error': 'Invalid E-mail'})
            user = authenticate(request, email=username, password=password)
        if user is None:
            return render(request, 'account/login.html', {'error': 'Invalid credentials'})
        auth_login(request, user)
        return redirect('home')


@require_http_methods(["GET"])
def logout(request):
    logout_handler(request)
    return redirect('home')


@require_http_methods(["GET", "POST"])
def register(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'GET':
        return render(request, 'account/register.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        matchEmail = request.POST.get('email-confirmation')
        password = request.POST.get('password')   # Set the hashed password
        matchPassword = request.POST.get('password-confirmation')
        if not is_valid_password(password) or not is_valid_username(username) or not is_valid_email(email) or password != matchPassword or email != matchEmail:
            return render(request, 'account/register.html', {'error': 'Invalid credentials'})
        try:
            user = User.objects.create_user(
                username=username, email=email, password=password)
            user.save()
            login(request, user)
            return redirect('home')
        except IntegrityError as e:
            if 'UNIQUE constraint failed: auth_user.email' in str(e):
                return render(request, 'account/login.html', {'error': 'Email already exists'})
            elif 'UNIQUE constraint failed: auth_user.username' in str(e):
                return render(request, 'account/login.html', {'error': 'Username already exists'})


@require_http_methods(["GET", "POST"])
def update(request):
    if not request.user.is_authenticated:
        return redirect('home')

    if request.method == 'GET':
        return render(request, 'account/update.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        matchUsername = request.POST.get('email-confirmation')
        password = request.POST.get('password')
        matchPassword = request.POST.get('password-confirmation')
        if not is_valid_password(password) or not is_valid_username(username) or password != matchPassword or username != matchUsername:
            return render(request, 'account/update.html', {'error': 'Invalid Data'})

        user = request.user
        user.username = username
        user.set_password(password)  # Set the hashed password
        user.save()
        return redirect('home')

core/views.py
from django.shortcuts import render

# Create your views here.

room/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import redirect
from .models import Room


def home(request):
    if not request.user.is_authenticated:
        return redirect("account:login")
    rooms = Room.objects.all()
    return render(request, 'index.html', {'rooms': rooms})


def room(request, slug):
    if not request.user.is_authenticated:
        return redirect("account:login")
    room = Room.objects.get(slug=slug)
    return render(request, 'room/room.html', {'room': room})

the_project/views.py
from django.shortcuts import render
from room.models import Room


def home(request):
    rooms = Room.objects.all()
    return render(request, 'index.html', {'rooms': rooms})

views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    pass
    return render(request, 'room/home.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% include  'partials/_head.html' %}
  <title>
    {% block title %}
    
    {% endblock %}
  </title>
</head>
<body class="container W100 bg-black-4">
  {% include  'partials/_header.html' %}
  {% block content %}

  {% endblock %}
  {% include  'partials/_footer.html' %}
  {% block scripts %}
  {% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content%}

<ul class="line justify-center w100 text-center mt-25-inheritance font-1 line mx-20-s-inheritance">
        {% for room in rooms %}
                <li class="w100 w40-s w25-m w20-l bg-white radius-3">
                        <h2 class="font-xxl mb-10">{{room.name}}</h2>
                        <a href="{% url 'room:room' room.slug %}" class="inline-block py-10 radius-3 px-20 bg-black-5 white font-m mb-15">Enter Chat</a>
                </li>
        {% endfor %}
</ul>
{% endblock %}

templates/partials/_head.html
{% load static %}

<link rel="stylesheet" href="{% static 'eccentric/main.css' %}">


<link rel="stylesheet" href="{% static 'eccentric/css/color/bgColor.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/color/fontColor.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/color/placeholderColor.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/color/rootColor.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/general/normalize.css' %}">

<link rel="stylesheet" href="{% static 'eccentric/css/textTag/button.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/textTag/border.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/textTag/font.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/textTag/radius.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/textTag/input.css' %}">

<link rel="stylesheet" href="{% static 'eccentric/main.css' %}">


<link rel="stylesheet" href="{% static 'eccentric/css/size/height.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/size/margin.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/size/padding.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/size/width.css' %}">
<link rel="stylesheet" href="{% static 'eccentric/css/display/flex.css' %}">

<link rel="stylesheet" href="{% static 'style.css' %}">

templates/partials/_header.html
<header>
  <div class="text-center relative w100">
    <h1 class="font-xxxl white font-3">Chat With Django</h1>
    <div class="right-middle mr-40">
      <ul class="flex w100 mx-5-inheritance">
        {% if user.is_authenticated %}
        <li><a href="{% url 'account:logout' %}"
            class="white font-xl p-10 text-center radius-3 bg-red font-2">Logout</a></li>
        <li><a href="{% url 'account:update' %}"
            class="white font-xl p-10 text-center radius-3 bg-green-4 font-2">Update</a></li>
        {% else %}
        <li><a href="{% url 'account:login' %}"
            class="white font-xl p-10 text-center radius-3 bg-green-10 font-2">Login</a>
        </li>
        <li><a href="{% url 'account:register' %}"
            class="font-xxxl inline-block py-10 w100 radius-5 text-center bg-green-10 white">Register</a></li>
        {% endif %}
        <li>
          <a href="{% url 'home' %}" class="white font-xl p-10 text-center radius-3 bg-black-10 font-2">Home</a>
        </li>
      </ul>
    </div>
  </div>

</header>

templates/room/room.html
{% extends 'base.html' %}


{% block content%}
<div class="chat-messages">

  <form action="." method="POST">
    <input type="text" name="content" id="chat-message-input">
    <button type="submit" id="chat-message-submit">Enviar</button>
  </form>
</div>


{% endblock %}
{% block scripts %}
{{ room.slug|json_script:"json-roomname"}}
{{ request.user.Username|json_script:"json-username"}}
<script>
  const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
  const userName = JSON.parse(document.getElementById('json-username').textContent);
  console.log(roomName);
  const chatSocket = new WebSocket(
    'ws://'
    + window.location.host
    + '/ws/'
    + roomName
    + '/'
  );
  chatSocket.onmessage = (e) => {
    const message = JSON.parse(e.data);
    if (data.message) {
      let html = '<div>';
      html += '<p>' + data.username + '</p>';
      html + '<p>' + data.message + '</p>';
      html += '</div>';
    }
    else {
      console.log('Did not receive message:', message);
    }
    console.log('Received message:', message);
  };

  chatSocket.onclose = (e) => console.log('onclose', e);

  //

  document.querySelector('#chat-message-submit').onclick = (e) => {
    e.preventDefault();
    const messageInputDom = document.querySelector('#chat-message-input');
    const message = messageInputDom.value;
    chatSocket.send(JSON.stringify({
      'message': message,
      'username': userName,
      'room': roomName
    }))
    messageInputDom.value = '';
  } 
</script>
{% endblock %}